### ISSUE TITLE
Mission pack textures

### ISSUE THREAD

**Issue by jlanzobr** [Calinou/quake2-neural-upscale#6] opened 2020-10-03 20:10 UTC
This project is the best texture replacement. It keeps the feel of the original game without so much blur. Please apply the same treatment to the mission packs so that Quake 2 may live on!

**Comment by Calinou** [comment] 2020-10-03 20:14
Duplicate of https://github.com/Calinou/quake2-neural-upscale/issues/1. I plan to do it in the long term, but I don't have time to look into it right now.

**Closed as completed by Calinou** 2020-10-03 20:14 UTC
Labels: duplicate, enhancement
